__include__: ../abstract.yaml
exp:
  outpath: logs/f30k_precomp/adapt_t2i/latent_1536/
  resume: null # last, best_[...], or empty (from scratch)
model:
  latent_size: 1536
  freeze_modules: [model.txt_enc.embed.glove,]
  txt_enc:
    name: gru_glove
    params:
      embed_dim: 300
      use_bi_gru: true
      glove_path: '.vocab_cache/glove_f30k_precomp.json.pkl'
      add_rand_embed: true
    pooling: none
    devices: [cuda,]
  img_enc:
    name: simple
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: none
  similarity:
    name: adapt_t2i
    params:
      latent_size: 1536
      k: 1
      gamma: 10
      norm_output: True
      device: cuda # FIXME
    device: cuda # FIXME
optimizer:
  name: adamax
  params:
    lr: 0.001 # 7e-4
    gradual_warmup_steps: [0.5, 2.0, 4000] #torch.linspace
    lr_decay_epochs: [10000, 20000, 3000] #range
    lr_decay_rate: .25
  lr_scheduler: 
    name: null
    params:
      step_size: 1000
      gamma: 1      
  grad_clip: 2.
