exp:
  resume: null # last, best_[...], or empty (from scratch)
dataset:  
  vocab_paths: [.vocab_cache/coco_precomp.json,]
  text_repr: word
  loader_name: precomp
  train:
    workers: 1
    batch_size: 128
  val:
    workers: 1
    batch_size: 64
model:
  latent_size: 1024
  freeze_modules: []  
  txt_enc:
    name: gru
    params:
      embed_dim: 300
      use_bi_gru: true
    pooling: lens
    devices: [cuda,]
  img_enc:
    name: vsepp_precomp
    params:
      img_dim: 2048
    devices: [cuda,]
    pooling: mean    
  similarity:
    name: cosine
    params:
      device: cuda # FIXME
    device: cuda # FIXME
  criterion:
    margin: 0.2
    max_violation: True
    beta: 0.991
optimizer:
  name: adam
  params:
    lr: 0.0006
  lr_scheduler:
    name: step
    params:
      step_size: 10000
      gamma: 0.1
  grad_clip: 2.
engine:
  eval_before_training: False
  debug: False
  print_freq: 10
  nb_epochs: 30
  early_stop: 50
  valid_interval: 500
